// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGxejiGcNHmTw6YAocdpjIAe_tlQ0C-LY',
    appId: '1:890298492825:web:73538725918a07d6309508',
    messagingSenderId: '890298492825',
    projectId: 'homework4-c0e35',
    authDomain: 'homework4-c0e35.firebaseapp.com',
    storageBucket: 'homework4-c0e35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEl4OdP7i7fxcXIlZjy0q4ynczk10p-ik',
    appId: '1:890298492825:android:3f0d6715a3f1db81309508',
    messagingSenderId: '890298492825',
    projectId: 'homework4-c0e35',
    storageBucket: 'homework4-c0e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMpDAU8ml0GKWBPQf_sn1hg5o-uKWPqis',
    appId: '1:890298492825:ios:211fe7bcd36da4b9309508',
    messagingSenderId: '890298492825',
    projectId: 'homework4-c0e35',
    storageBucket: 'homework4-c0e35.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMpDAU8ml0GKWBPQf_sn1hg5o-uKWPqis',
    appId: '1:890298492825:ios:211fe7bcd36da4b9309508',
    messagingSenderId: '890298492825',
    projectId: 'homework4-c0e35',
    storageBucket: 'homework4-c0e35.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGxejiGcNHmTw6YAocdpjIAe_tlQ0C-LY',
    appId: '1:890298492825:web:315ba9cb6037cfdb309508',
    messagingSenderId: '890298492825',
    projectId: 'homework4-c0e35',
    authDomain: 'homework4-c0e35.firebaseapp.com',
    storageBucket: 'homework4-c0e35.firebasestorage.app',
  );
}
